### ISSUE TITLE
Error decoding localhost address on macOS

### ISSUE THREAD

**Issue by mcdado** [traviscross/mtr#313]
![Screenshot of the error: "Error decoding localhost address. mtr: Failure to start mtr-packet: Invalid Argument"](https://user-images.githubusercontent.com/898057/62471732-92135600-b79d-11e9-9e7f-4d5d612199aa.png)

> Error decoding localhost address.
> mtr: Failure to start mtr-packet: Invalid Argument

Installed via homebrew, with /usr/local/sbin in $PATH. Running with zsh but reproduced in bash too.

**Comment by rewolff** [comment]
Your "mtr" binary needs to execute "mtr-packet" to do the low-level stuff. The error means it can't find it. Can YOU find mtr-packet? Where is it? Is that in your path?

**Comment by mcdado** [comment]
```
sudo mtr-packet 
Password:
Error decoding localhost address
```

**Comment by rewolff** [comment]
Hi, 
I've produced a patch, that will hopefully explain better what goes wrong. 
I've had to upload it with the "log" extension because ".diff" is not accepted by github. patch -p1 < probe_err.log  should patch your sources. 

[probe_err.log](https://github.com/traviscross/mtr/files/3468499/probe_err.log)

**Comment by cebor** [comment]
I have the same issue since the last mtr update via brew.

I also added some addresses for 127.0.0.1 to my /etc/hosts, maybe this is the issue?

**Comment by rewolff** [comment]
can you check the patch and try to rebuild?

**Comment by mcdado** [comment]
```
➜  mtr git:(master) git apply ~/Downloads/probe_err.diff
```

```
➜  mtr git:(master) ✗ ./bootstrap.sh && ./configure && make
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-apple-darwin18.7.0
checking host system type... x86_64-apple-darwin18.7.0
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking size of unsigned char... 1
checking size of unsigned short... 2
checking size of unsigned int... 4
checking size of unsigned long... 8
checking arpa/nameser_compat.h usability... yes
checking arpa/nameser_compat.h presence... yes
checking for arpa/nameser_compat.h... yes
checking curses.h usability... yes
checking curses.h presence... yes
checking for curses.h... yes
checking cursesX.h usability... no
checking cursesX.h presence... no
checking for cursesX.h... no
checking error.h usability... no
checking error.h presence... no
checking for error.h... no
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking linux/icmp.h usability... no
checking linux/icmp.h presence... no
checking for linux/icmp.h... no
checking linux/errqueue.h usability... no
checking linux/errqueue.h presence... no
checking for linux/errqueue.h... no
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking ncurses/curses.h usability... no
checking ncurses/curses.h presence... no
checking for ncurses/curses.h... no
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking socket.h usability... no
checking socket.h presence... no
checking for socket.h... no
checking sys/cdefs.h usability... yes
checking sys/cdefs.h presence... yes
checking for sys/cdefs.h... yes
checking sys/limits.h usability... no
checking sys/limits.h presence... no
checking for sys/limits.h... no
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking stdio_ext.h usability... no
checking stdio_ext.h presence... no
checking for stdio_ext.h... no
checking for sys/types.h... (cached) yes
checking sys/xti.h usability... no
checking sys/xti.h presence... no
checking for sys/xti.h... no
checking values.h usability... no
checking values.h presence... no
checking for values.h... no
checking for __fpending... no
checking for fcntl... yes
checking for error... no
checking for verr... yes
checking for verrx... yes
checking for vwarn... yes
checking for vwarnx... yes
checking for getopt_long... yes
checking for floor in -lm... yes
checking for gtk+-2.0... no
checking for library containing initscr... -lncurses
checking for cap_set_proc in -lcap... no
checking for socket... yes
checking for gethostbyname... yes
checking for res_query... yes
checking for dn_expand in -lresolv... yes
checking whether errno is declared... yes
checking for socklen_t... yes
checking for time_t... yes
checking for C flags to get more warnings... -Wall -Wno-pointer-sign
build options:
--------------
ipv6    :yes
ipinfo  :yes
ncurses :yes
gtk     :no
cap     :
libs    :-lncurses -lm 
cflags  :-g -O2 -Wall -Wno-pointer-sign
--------------
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CCLD     mtr
  CC       packet/packet.o
  CC       packet/command.o
  CC       packet/probe.o
packet/probe.c:320:26: warning: unused variable 'srcaddr6' [-Wunused-variable]
    struct sockaddr_in6 *srcaddr6;
                         ^
packet/probe.c:319:25: warning: unused variable 'srcaddr4' [-Wunused-variable]
    struct sockaddr_in *srcaddr4;
                        ^
2 warnings generated.
  CC       packet/construct_unix.o
  CC       packet/deconstruct_unix.o
  CC       packet/probe_unix.o
  CC       packet/wait_unix.o
  CCLD     mtr-packet
```

```
➜  mtr git:(master) ✗ sudo ./mtr www.google.com            
Error decoding localhost address
mtr: Failure to start mtr-packet: Invalid argument
➜  mtr git:(master) ✗ sudo ./mtr-packet www.google.com 
Error decoding localhost address (find source address)
```

**Comment by rewolff** [comment]
OK. Great. Thanks. I'll have a further "debugging patch" for you shortly. It will include the previous patch, so you'll need to unroll that one.

**Comment by rewolff** [comment]
[probe_err2.log](https://github.com/traviscross/mtr/files/3472318/probe_err2.log)

**Comment by mcdado** [comment]
```
sudo ./mtr-packet www.google.com
Error decoding localhost address (connect failed)
```

**Comment by rewolff** [comment]
haha! that's fast! 
(Here in the Netherlands, a (at least) 30-year-old advertizement had the delivery truck arrive TOOOT TOOOOT  while the client was putting down the phone, so we say: "tooot, toot, that was fast!")
Ok. Now we know the line that fails. Let's analize what goes wrong.

**Comment by mcdado** [comment]
I'm checking out old tags, some releases don't build on macOS, but in general they all seem to have the same problem. Maybe it is related to an update in macOS?

> (Here in the Netherlands, a (at least) 30-year-old advertizement had the delivery truck arrive TOOOT TOOOOT while the client was putting down the phone, so we say: "tooot, toot, that was fast!")

Ahah good to know, I'll keep it mind! 😄

**Comment by rewolff** [comment]
Hopefully the last one to try... 
[probe_err3.log](https://github.com/traviscross/mtr/files/3472451/probe_err3.log)

**Comment by mcdado** [comment]
Yeah of course, I meant it in a way to point to a possible solution 😅 

```
sudo ./mtr-packet github.com
Error decoding localhost address (connect failed/Invalid argument)
```

**Comment by lembacon** [comment]
I think the issue is related to `sockaddr_addr_size`,

```c
unsigned int sockaddr_addr_size(const void *x)
{
	if( x == NULL )
		return 0;
	if( ((struct sockaddr *)(x))->sa_family == AF_INET )
	{
		return sizeof(struct in_addr);
	}else
	if( ((struct sockaddr *)(x))->sa_family == AF_INET6 )
	{
		return sizeof(struct in6_addr);
	}
	return 0;
}
```

Shouldn't this return the size of `struct sockaddr_in` or `struct sockaddr_in6`?

**Comment by lembacon** [comment]
Pull request submitted as #315.

**Comment by rewolff** [comment]
OK. Thanks. Sorry for sounding "agressive". Alas, not helpful this time (I think, at the moment) but such tips should always be welcome even if they don't help. So thanks again. :-)

Now.... What we have is that MacOS is returning: "invalid argument" on the "connect" system call where that used to work. It's saying something about the arguments is wrong, Alas I still don't know what could be causing THAT. :-( . Maybe @matt-kimball knows what the issue could be?

Matt... it is THIS line https://github.com/traviscross/mtr/blob/master/packet/probe.c#L333
that gets the "EINVAL" error return.

**Comment by mcdado** [comment]
I tried pulling the latest master with #315 merged, but the problem persists.

```
➜  mtr git:(master) sudo ./mtr-packet www.google.com     
^C
➜  mtr git:(master) sudo ./mtr www.google.com 
Error decoding localhost address
mtr: Failure to start mtr-packet: Invalid argument
```

mtr-packet seems to hang, while mtr straight up fails

**Comment by lembacon** [comment]
@mcdado Because `mtr` still picks up the broken `mtr-packet` in your `PATH`.

**Comment by rewolff** [comment]
A few posts back, you've shown that you were running the system (installed) mtr-packet, while testing the new mtr-with-patches. This when you run mtr-packet as it is supposed to: as a subprocess of mtr. 

When you manually ran mtr-packet, you were running the right one. At that point in time that didn't really matter. I had enough info to decode what was going on. Now it's starting to matter.... So the mtr-packet you start from "mtr" is the old one that doesn't work, and the new one you start manually seems to hang because it doesn't fail: it works! 
And lembacon is faster at typing shorter messages. :-)

**Comment by mcdado** [comment]
![Screenshot 2019-08-06 at 18 45 19](https://user-images.githubusercontent.com/898057/62559037-7631b200-b87a-11e9-9d76-ee2392a00ccc.png)

Glorious!

**Comment by lembacon** [comment]
Actually I've just merged Homebrew/homebrew-core#42857, you could run `brew update && brew upgrade mtr` now. 😸

**Comment by JohnFHall** [comment]
Apparently I can't add this still existing issue (on Mac, at least), as the issue is closed.
Oh well, all too hard for me.
Just to state the obvious:-
mtr-packet is in my path, and the current one is still:-
MacPRO:~ johnhall$ ls -la `which mtr-packet`
-rwsr-sr-x  1 root  admin  30212 10 Aug 04:53 /opt/local/sbin/mtr-packet
MacPRO:~ johnhall$ mtr-packet
Error decoding localhost address

**Comment by mcdado** [comment]
> Apparently I can't add this still existing issue (on Mac, at least), as the issue is closed.
> Oh well, all too hard for me.
> Just to state the obvious:-
> mtr-packet is in my path, and the current one is still:-
> MacPRO:~ johnhall$ ls -la `which mtr-packet`
> -rwsr-sr-x 1 root admin 30212 10 Aug 04:53 /opt/local/sbin/mtr-packet
> MacPRO:~ johnhall$ mtr-packet
> Error decoding localhost address

How did you install mtr? from the /opt/local path i guess not from Homebrew. The updated version in Homebrew. Otherwise you can uninstall the version you currently have installed (macports?) and clone the repo from Github and from the git repo directory run:

```
./bootstrap.sh && ./configure && make && make install
```

**Comment by JohnFHall** [comment]
Thank you for the answer. Installed via macports. (v0.93). I'll maybe wait till macports update the source...

**Comment by JohnFHall** [comment]
mtr under Macports v0.93.

I’ll probably wait till that source is updated.

Regards,
John

**Comment by SaintBol** [comment]
> Thank you for the answer. Installed via macports. (v0.93). I'll maybe wait till macports update the source...

macport uses the released source at ftp://ftp.bitwizard.nl/mtr/. They'll probably rollback to 0.92, I guess.

**Comment by expelledboy** [comment]
I am still getting this, using mtr v0.93 built with nixos on darwin.

```sh
➜  ~ which mtr-packet
/Users/anthony/.nix-profile/bin/mtr-packet
➜  ~ which mtr
/Users/anthony/.nix-profile/bin/mtr
➜  ~ echo $PATH
/Users/anthony/.nix-profile/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
➜  ~ sudo mtr-packet www.google.com
Error decoding localhost address
➜  ~ mtr --version
mtr 0.93
```

**Comment by expelledboy** [comment]
This is the [build spec](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/mtr/default.nix) for mtr in nixpkgs.

**Comment by rwanyoike** [comment]
https://github.com/NixOS/nixpkgs/pull/73475 has been merged to patch the nix package!

**Comment by mdavids** [comment]
Mtr 0.2 on Debian 10 (Buster) IPv6-only has the same problem. 

It has no 127.0.0.1 (only ::1).
Neither on the lo-interface, nor in /etc/hosts.

Could that be the reason?
