### ISSUE TITLE
My default gateway is listed twice in the CSV return

### ISSUE THREAD

**Issue by eksantrik** [traviscross/mtr#342]
I compiled the latest version of mtr and doing some tests from my laptop. My next hop is my wifi router, and every once in a while I see that it pops up in the list more than once. Is this a known issue?

/root/downloads/mtr-0.93/mtr zoom.us -C -T -P 443

Mtr_Version,Start_Time,Status,Host,Hop,Ip,Loss%,Snt, ,Last,Avg,Best,Wrst,StDev,
MTR.UNKNOWN,1585927882,OK,zoom.us,1,testwifi.here,10.00,10,1,7016.19,2510.38,1004.89,7016.19,1939.88
MTR.UNKNOWN,1585927882,OK,zoom.us,2,level3-ic-319314-chi-b21.c.telia.net,90.00,10,9,2545.76,2545.76,2545.76,2545.76,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,3,???,100.00,10,10,0.00,0.00,0.00,0.00,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,4,st.laurent-ottawa.tsi-rcable.tor2.teksavvy.com,0.00,10,0,27.13,30.22,22.72,65.25,12.67
MTR.UNKNOWN,1585927882,OK,zoom.us,5,ae1-0-bdr01-tor.teksavvy.com,0.00,10,0,29.00,27.16,23.48,31.04,2.66
MTR.UNKNOWN,1585927882,OK,zoom.us,6,ae12-0-bdr01-tor.teksavvy.com,60.00,10,6,23.27,27.37,22.63,33.30,5.26
MTR.UNKNOWN,1585927882,OK,zoom.us,7,???,100.00,10,10,0.00,0.00,0.00,0.00,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,8,testwifi.here,90.00,10,9,2575.33,2575.33,2575.33,2575.33,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,9,???,100.00,10,10,0.00,0.00,0.00,0.00,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,10,???,100.00,10,10,0.00,0.00,0.00,0.00,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,11,testwifi.here,90.00,10,9,2440.22,2440.22,2440.22,2440.22,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,12,???,100.00,10,10,0.00,0.00,0.00,0.00,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,13,???,100.00,10,10,0.00,0.00,0.00,0.00,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,14,???,100.00,10,10,0.00,0.00,0.00,0.00,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,15,???,100.00,10,10,0.00,0.00,0.00,0.00,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,16,???,100.00,10,10,0.00,0.00,0.00,0.00,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,17,testwifi.here,87.50,8,7,3079.55,3079.55,3079.55,3079.55,0.00
MTR.UNKNOWN,1585927882,OK,zoom.us,18,???,100.00,6,6,0.00,0.00,0.00,0.00,0.00

**Comment by Gowee** [comment]
I see there are four repeated occurrences of `testwifi.here`. Is it possible that there happen to be some hosts on the path sharing the same LAN IP address range, which are all resolved via PTR to `testwifi.here`, as your gateway?

**Comment by ttrading** [comment]
Not likely.. Even when I disable my dns resolution, I am still getting 10.10.10.1 (testwifi.here) many times in the list sometimes. It does not always happen.

I read that MTR sends the requests in bulk to be efficient and this may be the root cause of my issue. Can someone suggest me a systematic approach to avoid this issue? Should I decrease the number of packets or increase/decrease the timeouts?

Thanks,

**Comment by Gowee** [comment]
Though I have no suggestion, the problem sounds like #344 which I am encountering. In my case, when I run multiple mtr instances simultaneously, their outputs get mixed up in a mess. 

Every ICMP packet could have been identified according to their identifier and sequence number which is long enough to avoid collisions.

**Comment by ttrading** [comment]
@Gowee , you might be right because I have multiple instances of mtr running via cron jobs.

**Comment by lingooz** [comment]
@Gowee I have got the same issue. I run a few mtr instances at same time in different VM. But it looks only one vm get this issue. However, I turn the bad one to one instance at a time. The issue's gone.
